apiVersion: v1
kind: Service
metadata:
  name: employee-app
  namespace: emp-directory
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080   # reachable at http://<node-ip>:30080
